# This file is machine-generated - editing it directly is not advised

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Raw2CSV]]
deps = ["DelimitedFiles"]
path = ".."
uuid = "10db5394-6fb8-4366-bb28-af2089be88a3"
version = "0.1.0"
